### ISSUE TITLE
Mapping problem in keyboard-apu from 48-key to Brazilian 47-key layout

### ISSUE THREAD

**Issue by rueter** [giellalt/keyboard-apu#1]
The Apurinã keyboard should have tilde combinations for all vowels and a modifier letter apostrophe to mark glottal stop. In addition we want circumflex, grave, acute and diaereses.

This äëïöüÿ ãẽĩõũỹ àèìòùỳ áéíóúý works on my M2, Sonoma 14.3.1 in Finland, but it does not quite map to the Brazilian Mac Air used by Sidney Facundes, hence a distinction in the names apu_FI and apu_BR.
Note, for example, that the FI-board shows both sides of the square brackets in the QWERTY row, but the BR-board moves the right-hand bracket to the beginning of the next line.
Please, ask for additional information.

![apu_BR_Divvun_default](https://github.com/giellalt/keyboard-apu/assets/14276164/4c1a3223-69a2-4723-babb-1ace951c4ba6)
![apu_BR_Divvun_shift](https://github.com/giellalt/keyboard-apu/assets/14276164/6b10572d-4900-4a89-a8ee-9c400cbf3abb)
![apu_BR_Divvun_alt_shift](https://github.com/giellalt/keyboard-apu/assets/14276164/bd9eae7e-2fd5-46b8-bdbe-5bec27b22dd8)
![apu_BR_Divvun_alt](https://github.com/giellalt/keyboard-apu/assets/14276164/473f1de2-e18a-4444-a2e2-c8f5d5b7af32)
<img width="589" alt="apu_FI_Divvun_default" src="https://github.com/giellalt/keyboard-apu/assets/14276164/1753615d-cd7c-493e-bf12-429e130a3903">
<img width="589" alt="apu_FI_Divvun_shift" src="https://github.com/giellalt/keyboard-apu/assets/14276164/91470cd3-1413-4843-a334-756488602874">
<img width="589" alt="apu_FI_Divvun_alt" src="https://github.com/giellalt/keyboard-apu/assets/14276164/dd5addd3-c044-4a0f-ba75-f6a4c0e0cf60">
<img width="589" alt="apu_FI_Divvun_alt_shift" src="https://github.com/giellalt/keyboard-apu/assets/14276164/fa33c625-0515-41ce-8994-b2b83655e9cd">

**Comment by rueter** [comment]
The por_BR board looks like this:
![por_BR_default](https://github.com/giellalt/keyboard-apu/assets/14276164/5bd5ef84-c5d8-4939-b96a-b6340083e8fe)
![por_BR_shift](https://github.com/giellalt/keyboard-apu/assets/14276164/190ea6aa-afb0-4b63-995a-7659fb0d2707)
![por_BR_alt_shift](https://github.com/giellalt/keyboard-apu/assets/14276164/a3a43717-5839-41c6-b09c-0631130bdf50)
![por_BR_alt](https://github.com/giellalt/keyboard-apu/assets/14276164/5fcaac85-6b30-4803-a8ff-08de8bab7f17)

**Comment by snomos** [comment]
I edited the layout file to be identical to Apple's Brasilian Portuguese, _as it appears on my computer, using an ISO keyboard_.

Cf https://github.com/giellalt/keyboard-apu/commit/190b7bcb0d2988daff1d31e2ae1bdac3f3da1094

It should produce all the accented vowels you desire, although the deadkeys are in different positions.

I did this for two reasons:
- I think it is wise to deviate as little as possible from the regular Brasilian keyboard as possible
- I want to debug our keyboard build process:
    - if the `kbdgen` tool is working correctly, then this version should look exactly as the por_BR keyboard above. If not, we have a known state to debug from, with no other changes than those produced by `kbdgen`

Do NOT change any deadkeys or anything else, just build this new version, and give it to Sidney, and ask him to take screen shots so that we can compare.

**Comment by rueter** [comment]
Now, there is only one difference observed in the layout.
On the por_BR keyboard tilde requires +shift ( see below).
Otherwise, the keyboard looks right and seems to work right.

![apu_Divvun_01_default](https://github.com/giellalt/keyboard-apu/assets/14276164/42efe362-b91c-4096-94e3-c8062a62132d)
![apu_Divvun_02_shift](https://github.com/giellalt/keyboard-apu/assets/14276164/3007d1b1-4ae0-43e7-b7ac-b2d0f145a9f8)
![apu_Divvun_03_alt](https://github.com/giellalt/keyboard-apu/assets/14276164/5b504c55-731f-4f55-a340-6327d79173d9)
![apu_Divvun_04_alt_shift](https://github.com/giellalt/keyboard-apu/assets/14276164/2f6c8614-0f48-48d4-a688-b5e4583bdde9)
![apu_Divvun_05_comb_view](https://github.com/giellalt/keyboard-apu/assets/14276164/ea91ab33-5bcf-477b-9540-7a0e79a4b022)
![por_BR_shift_for_tilde](https://github.com/giellalt/keyboard-apu/assets/14276164/8e2e64f2-f37f-4a23-befa-10f7aa43693e)

**Comment by snomos** [comment]
> Now, there is only one difference observed in the layout.
> On the por_BR keyboard tilde requires +shift ( see below).
> Otherwise, the keyboard looks right and seems to work right.

This is how it is on the Apple Brazilian keyboard. I want it to be identical with that one, and make sure it works everywhere the correct way before we start to change anything. And from the screen shots, it does not look like shift is required to get tilde.

On the other hand, it seems that the screen shots are not from the latest version that I pushed to GitHub, it contains deadkeys that I removed. Could you make sure that the version of the keyboard package is `0.1.1`, not `0.1.0`?

Whose computer are the screen shots from? It seems to be a Mac with an ANSI keyboard?

**Comment by rueter** [comment]
These pictures all come from Sidney's Mac Air.
Sidney says the shift for Tilde is standard.

**Comment by rueter** [comment]
Unable to generate macos version on own mac.
Have removed and reinstalled giellalt, and cloned 
Still get:
```
"/Users/jackrueter/Dropbox/Github/giellalt/keyboard-apu/apu.kbdgen"
thread 'main' panicked at src/build/macos/generate_macos.rs:486:25:
dead key `"` in target list but not the transforms.
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
make: *** [Makefile:604: mac] Error 101

```
Maybe you haven't pushed everything onto Github.
see also:
```
Github Bot: Check [Build keyboard: macos-latest - keyboard-apu](https://github.com/giellalt/keyboard-apu/runs/22033224856) completed (failure). ([b8aacd210c4](https://github.com/giellalt/keyboard-apu/commit/b8aacd210c4f77c029493e77e9ca933eab91cf9a))

Github Bot: Check [Build keyboard: windows-latest - keyboard-apu](https://github.com/giellalt/keyboard-apu/runs/22033225532) completed (failure). ([b8aacd210c4](https://github.com/giellalt/keyboard-apu/commit/b8aacd210c4f77c029493e77e9ca933eab91cf9a))
```
both have failed, with no push since

**Comment by snomos** [comment]
> Unable to generate macos version on own mac.

Sorry, my bad. I have fixed it, and also replaced the Sámi flag with the UN flag. New version is 0.1.2, and it has already built successfully for Mac, and is available in Divvun Manager.
